# Generated by Django 4.1.1 on 2023-01-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_alter_issue_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('IO', 'iOS'), ('AN', 'Android')], max_length=2),
        ),
    ]
